namespace HotelBob
{class Drzave{
        public static string[] drzave = {"Afganistan", "Albanija", 
            "Alžir", "Angola", "Andora", "Antigva i Barbuda", "Argentina", 
            "Australija", "Austrija", "Azerbejdžan", "Bahami", "Bahrein", 
            "Bangladeš", "Barbados", "Belgija", "Belize", "Belorusija", "Benin", 
            "Bocvana", "Bolivija", "Bosna i Hercegovina", "Brazil", "Brunei,", 
            "Bugarska", "Burkina Faso", "Burundi", "Butan", "Centralnoafrička Republika",
            "Crna Gora", "Čad", "Češka Republika", "Čile", "Danska", "Dominika", 
            "Dominikanska Republika", "Džibuti", "Egipat", "Ekvador", 
            "Ekvatorijalna Gvineja", "El Salvador", "Eritreja", "Estonija", 
            "Etiopija", "Fidži", "Filipini", "Finska", "Francuska", "Gabon", 
            "Gambija", "Gana", "Grčka", "Grenada", "Gruzija", "Gvajana", "Gvatemala", 
            "Gvineja", "Gvineja Bisau", "Haiti", "Holandija", "Honduras", "Hrvatska", 
            "Indija", "Indonezija", "Irak", "Iran", "Irska", "Island", "Istočni Timor"
            , "Italija", "Izrael", "Jamajka", "Japan", "Jemen", "Jermenija", "Jordan",
            "Južnoafrička Republika", "Južna Koreja", "Južni Sudan", "Kamerun", "Kanada", 
            "Katar", "Kazahstan", "Kenija", "Kina", "Kipar", "Kirgistan", "Kiribati", 
            "Kolumbija", "Komori", "Republika Kongo", "Demokratska Republika Kongo", 
            "Kostarika", "Kuba", "Kuvajt", "Laos", "Lesoto", "Letonija", "Liban", 
            "Liberija", "Libija", "Lihtenštajn", "Litvanija", "Luksemburg", "Madagaskar", 
            "Mađarska", "Makedonija", "Malavi", "Maldivi", "Malezija", "Mali", "Malta", 
            "Maroko", "Maršalska Ostrva", "Mauricijus", "Mauritanija", "Meksiko", 
            "Mikronezija", "Mjanmar", "Moldova", "Monako", "Mongolija", "Mozambik", 
            "Namibija", "Nauru", "Nemačka", "Nepal", "Niger", "Nigerija", "Nikaragva", 
            "Norveška", "Novi Zeland", "Obala Slonovače", "Oman", "Pakistan", "Palau", 
            "Panama", "Papua Nova Gvineja", "Paragvaj", "Peru", "Poljska", "Portugal", 
            "Ruanda", "Rumunija", "Rusija", "Ruanda", "Rumunija", "Rusija", "San Marino", 
            "Samoa", "Sao Tome i Principe", "Saudijska Arabija", "Sejšeli", "Senegal", 
            "Severna Koreja", "Sijera Leone", "Singapur", "Sirija", "Sjedinjene Države", 
            "Slovačka", "Slovenija", "Solomonska Ostrva", "Somalija", "Srbija", "Sudan", 
            "Surinam", "Svazilend", "Sveta Lucija", "Sveti Vincent i Grenadini", 
            "Sveti Kits i Nevis", "Švajcarska", "Švedska", "Španija", "Šri Lanka", 
            "Tadžikistan", "Tajland", "Tanzanija", "Togo", "Tonga", "Trinidad i Tobago", 
            "Tunis", "Turkmenistan", "Turska", "Tuvalu", "Uganda", 
            "Ujedinjeni Arapski Emirati", "Ujedinjeno Kraljevstvo", 
            "Ujedinjeno Kraljevstvo", "Ukrajina", "Urugvaj", "Uzbekistan", 
            "Vanuatu", "Venezuela", "Vijetnam", "Zambija", "Zelenortska Ostrva", "Zimbabve" 
        };}}